language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t leon/docker-react -f Dockerfile.dev .   
  
script: 
  - docker run -e CI=true leon/docker-react npm run test